version: '3.9'

volumes:
  data:

services:
  database:
    image: mysql
    hostname: mysql
    ports:
      - '3309:3306'
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: secret

  mockserver:
    image: mockserver
    build: ../mock-server
    hostname: mockserver
    ports:
      - '3000-3100:3000-3100'

  service-poller-be:
    image: service-poller-be
    build: ../service-polling-be
    hostname: mockserver
    ports:
      - '8080:8080'